version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: design-postgres

    restart: unless-stopped

    environment:
      POSTGRES_USER: medusa
      POSTGRES_PASSWORD: medusa
      POSTGRES_DB: medusa

    ports:
      - "5432:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: design-redis

    restart: unless-stopped

    ports:
      - "6379:6379"

    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  redis-data:
